name: Repeat Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        bundler-cache: true
    - name: build gem
      run: bundle exec rake build
    - name: install gem
      run: gem install ./pkg/*.gem
    - name: Run Repeat Test
      run: bundle exec repeat_test
